### ISSUE TITLE
W1 Cornerstone

### ISSUE THREAD

**Issue by 100pearl** [dev-lumanlab/mind-battery-app#1]
## 📝 Tasks

- [ ] Init Project
- [ ] absolute path
- [ ] asset reusable renderer
- [ ] dependency list update
- [ ] static properties as Constants 
- [ ] set up directories
- [ ] embed util functions
